FROM node:12

COPY . .

ARG AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ARG EMAIL_PASSWORD=$EMAIL_PASSWORD

ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV EMAIL_PASSWORD=$EMAIL_PASSWORD

CMD ["env"]
# CMD ["node", "handler.js"]
