name: scraper

on:
  repository_dispatch:
  schedule:
    - cron: "0,30 * * * *"

jobs:
  product-watcher:
    runs-on: ubuntu-latest
    name: Build and run scraper
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: npm install
        working-directory: ./scraper

      - name: Docker run step
        uses: ./scraper
        id: product-watcher
        env:
          NODE_ENV: production
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
