name: scraper

on:
  repository_dispatch:
  # schedule:
  #   - cron: "0 */12 * * *"

jobs:
  product-watcher:
    runs-on: ubuntu-latest
    name: Build and run scraper
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build and run
        uses: ./
        id: product-watcher
